---
#
# packages_install
#
__packages_install_all:
  - install-from-group-all

packages_install: "{{ __packages_install_all }}"

#
# packages_remove
#
__packages_remove_all:
  - remove-from-group-all

packages_remove: "{{ __packages_remove_all }}"

#
# system_keyboard
#
system_keyboard: fi
system_font: eurlatgr
