---
- name: Debug playbook example
  hosts: all
  become: false
  gather_facts: true
  tasks:
    - name: Display Ansible configuration details
      debug:
        msg: |
          ansible_version: {{ ansible_version }}
          ansible_config_file: {{ ansible_config_file }}
          ansible_inventory_sources: {{ ansible_inventory_sources }}
          ansible_play_hosts_all: {{ ansible_play_hosts_all }}
          ansible_play_batch: {{ ansible_play_batch }}
      run_once: true

    - name: Display Ansible host groups
      debug:
        var: groups
      run_once: true

    - name: Display variable names
      debug:
        msg: "{{ lookup('varnames', '.+').split(',') | sort }}"

    - name: Display facts
      debug:
        var: ansible_facts

    - name: Display environment
      debug:
        var: environment
