---
- name: Example playbook
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Display Ansible configuration details
      debug:
        msg: |
          ansible_version: {{ ansible_version }}
          ansible_config_file: {{ ansible_config_file }}
          ansible_inventory_sources: {{ ansible_inventory_sources }}
          ansible_play_hosts_all: {{ ansible_play_hosts_all }}
          ansible_play_batch: {{ ansible_play_batch }}
      run_once: true

    - name: Display Ansible host groups
      debug:
        var: groups
      run_once: true

    - name: Display configured timezone
      debug:
        var: timezone

    - name: Display packages to be installed
      debug:
        var: packages_install

    - name: Display packages to be removed
      debug:
        var: packages_remove

    - name: Check host reachable
      wait_for:
        port: 22
        search_regex: OpenSSH
        timeout: 30

    - name: Check host access
      ping:

    - name: Check user privileges
      become: true
      command: /usr/bin/whoami
      register: whoami_output
      failed_when: whoami_output.stdout != 'root'
      changed_when: false
