---
- name: Example playbook
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Display Ansible configuration details
      ansible.builtin.debug:
        msg: |
          ansible_version: {{ ansible_version }}
          ansible_config_file: {{ ansible_config_file }}
          ansible_inventory_sources: {{ ansible_inventory_sources }}
          ansible_play_hosts_all: {{ ansible_play_hosts_all }}
          ansible_play_batch: {{ ansible_play_batch }}
      run_once: true

    - name: Display Ansible host groups
      ansible.builtin.debug:
        var: groups
      run_once: true

    - name: Display configured timezone
      ansible.builtin.debug:
        var: timezone

    - name: Display packages to be installed
      ansible.builtin.debug:
        var: packages_install

    - name: Display packages to be removed
      ansible.builtin.debug:
        var: packages_remove
