---
- name: Vars override example
  hosts: all
  become: true
  gather_facts: false
  vars:
    packages_remove:
      - remove-from-playbook
    packages_remove_display_results: true

  tasks:
    - name: Display timezone to be configured
      ansible.builtin.debug:
        var: timezone

    - name: Display keyboard to be configured
      ansible.builtin.debug:
        var: keyboard

    - name: Display packages to be installed
      ansible.builtin.debug:
        var: packages_install

    - name: Display packages to be removed
      ansible.builtin.debug:
        var: packages_remove
